'use client'

import {useEffect,useMemo,useState} from 'react'
import {supabase} from '../lib/supabase'

type Row=Record<string,any>
const today=()=>new Date().toISOString().slice(0,10)
const money=(n:number)=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Number(n||0))
const addDays=(s:string,n:number)=>{const d=new Date(s+'T12:00:00');d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}
const daysLeft=(s:string)=>Math.ceil((new Date(s+'T12:00:00').getTime()-Date.now())/86400000)

export default function App(){
 const [session,setSession]=useState<any>(null),[loading,setLoading]=useState(true),[tab,setTab]=useState('dashboard')
 const [data,setData]=useState<Row>({athletes:[],plans:[],memberships:[],payments:[],products:[],staff:[],staffPayments:[],notifications:[],sales:[],audit:[]})
 const [role,setRole]=useState('staff'),[staffRole,setStaffRole]=useState(''),[q,setQ]=useState(''),[modal,setModal]=useState(''),[f,setF]=useState<Row>({}),[msg,setMsg]=useState('')
 const base=process.env.NEXT_PUBLIC_BASE_PATH||''

 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);if(!data.session)setLoading(false)});const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);if(!s)setLoading(false)});return()=>l.subscription.unsubscribe()},[])
 useEffect(()=>{if(session)load()},[session])
 async function load(){
  setLoading(true)
  const [u,a,pl,m,p,pr,s,sp,n,sa,au]=await Promise.all([
   supabase.auth.getUser(),
   supabase.from('athletes').select('*').order('full_name'),
   supabase.from('membership_plans').select('*').order('price'),
   supabase.from('memberships').select('*').order('end_date',{ascending:false}),
   supabase.from('payments').select('*').order('paid_at',{ascending:false}),
   supabase.from('products').select('*,product_variants(*)').order('name'),
   supabase.from('staff_members').select('*').order('full_name'),
   supabase.from('staff_payments').select('*').order('paid_at',{ascending:false}),
   supabase.from('notifications').select('*').order('created_at',{ascending:false}).limit(100),
   supabase.from('sales').select('*').order('created_at',{ascending:false}).limit(100),
   supabase.from('audit_logs').select('*').order('created_at',{ascending:false}).limit(100)
  ])
  const user=u.data.user
  if(user){
   const prf=await supabase.from('profiles').select('role').eq('id',user.id).maybeSingle()
   setRole(prf.data?.role||'staff')
   const me=(s.data||[]).find((x:Row)=>x.email?.toLowerCase()===user.email?.toLowerCase())
   setStaffRole(me?.role||'')
  }
  setData({athletes:a.data||[],plans:pl.data||[],memberships:m.data||[],payments:p.data||[],products:pr.data||[],staff:s.data||[],staffPayments:sp.data||[],notifications:n.data||[],sales:sa.data||[],audit:au.data||[]})
  setLoading(false)
 }
 const canManage=role==='owner'||role==='admin', canOperate=canManage||role==='staff'
 const nav=canOperate?['dashboard','athletes','memberships','payments','products','staff','communications','audit']:['athletes']
 const labels:any={dashboard:'Dashboard',athletes:'Deportistas',memberships:'Membresías',payments:'Caja y pagos',products:'Productos e inventario',staff:'Personal',communications:'Comunicaciones',audit:'Auditoría'}
 const active=data.memberships.filter((m:Row)=>m.status==='active'&&m.end_date>=today())
 const exp=active.filter((m:Row)=>daysLeft(m.end_date)<=7).sort((a:Row,b:Row)=>a.end_date.localeCompare(b.end_date))
 const month=today().slice(0,7)
 const revenue=data.payments.filter((p:Row)=>p.status==='confirmed'&&p.paid_at?.slice(0,7)===month).reduce((n:number,p:Row)=>n+Number(p.amount||0),0)
 const pending=data.notifications.filter((n:Row)=>n.status==='pending').length
 const filtered=data.athletes.filter((a:Row)=>[a.full_name,a.document_number,a.phone,a.email,a.category,a.team].join(' ').toLowerCase().includes(q.toLowerCase()))
 const close=()=>{setModal('');setF({});setMsg('')}

 if(loading)return <div className="splash"><div><img src={base+'/logo.jpg'} className="brand brand-lg"/><p>Cargando RIVER Club OS…</p></div></div>
 if(!session)return <Login base={base}/>

 return <div className="app" style={{'--img-textura':'url('+base+'/textura.jpg)','--img-lineas':'url('+base+'/lineas.png)'} as any}>
  <aside>
   <img className="brand" src={base+'/logo.jpg'} alt="RIVER"/>
   <small>CLUB OS · {role.toUpperCase()}</small>
   <nav>{nav.map((n:string)=><button key={n} className={tab===n?'active':''} onClick={()=>setTab(n)}>{labels[n]}</button>)}</nav>
   <div className="sidebottom"><span>{session.user.email}</span><button onClick={()=>supabase.auth.signOut()}>Cerrar sesión</button></div>
  </aside>
  <main className="main">
   <header><div><small>RIVER VOLLEYBALL CLUB</small><h1>{labels[tab]}</h1></div><div className="actions">
    {tab==='athletes'&&canOperate&&<button onClick={()=>{setF({status:'active'});setModal('athlete')}}>+ Deportista</button>}
    {tab==='memberships'&&canOperate&&<button onClick={()=>{setF({start_date:today(),registration_amount:0});setModal('register')}}>+ Inscripción</button>}
    {tab==='payments'&&canOperate&&<button onClick={()=>{setF({status:'confirmed',paid_at:new Date().toISOString().slice(0,16)});setModal('payment')}}>+ Pago</button>}
    {tab==='products'&&canManage&&<button onClick={()=>{setF({name:'',sku:'',description:'',variants:[{size:'',price:0,stock:0}]});setModal('product')}}>+ Producto</button>}
    {tab==='staff'&&canManage&&<button onClick={()=>{setF({role:'trainer',rate_type:'monthly',payment_rate:0});setModal('staff')}}>+ Personal</button>}
   </div></header>
   {tab==='dashboard'&&<Dashboard data={data} active={active} exp={exp} revenue={revenue} pending={pending} onRenew={(m:Row)=>{setF({athlete_id:m.athlete_id,start_date:today()});setModal('renew')}} onTab={setTab}/>}
   {tab==='athletes'&&<Athletes rows={filtered} q={q} setQ={setQ} canManage={canManage} onEdit={(a:Row)=>{setF(a);setModal('athlete')}}/>}
   {tab==='memberships'&&<Memberships data={data} onRenew={(m:Row)=>{setF({athlete_id:m.athlete_id,start_date:today()});setModal('renew')}}/>}
   {tab==='payments'&&<Payments data={data}/>}
   {tab==='products'&&<Products data={data} canManage={canManage} onSale={(v:Row,p:Row)=>{setF({product:p,variant:v,qty:1,method:'cash'});setModal('sale')}} onAdjust={(v:Row)=>{setF({variant:v,quantity:0,notes:''});setModal('stock')}}/>}
   {tab==='staff'&&<Staff data={data} canManage={canManage} onPay={(s:Row)=>{setF({staff_id:s.id,amount:s.payment_rate,period_start:month+'-01',period_end:addDays(month+'-01',30),concept:'Honorarios',method:'transfer'});setModal('staffpay')}}/>}
   {tab==='communications'&&<Communications data={data} exp={exp} pending={pending} onQueue={async()=>{const r=await supabase.rpc('queue_membership_reminders');setMsg(r.error?.message||'Se agregaron '+(r.data||0)+' recordatorios a la cola.');alert(r.error?.message||'Cola actualizada');load()}}/>}
   {tab==='audit'&&<Audit rows={data.audit}/>}
  </main>
  {modal==='athlete'&&<Modal title={(f as any)['id']?'Editar deportista':'Nuevo deportista'} close={close}><AthleteForm f={f} setF={setF} save={async()=>{const payload:any={...f,full_name:(f as Row).full_name?.trim()};delete payload.id;delete payload.created_at;delete payload.updated_at;const r=(f as any)['id']?await supabase.from('athletes').update(payload).eq('id',(f as any)['id']):await supabase.from('athletes').insert(payload);if(r.error)setMsg(r.error.message);else{close();load()}}} msg={msg}/></Modal>}
  {modal==='register'&&<Modal title="Nueva inscripción" close={close}><Register data={data} f={f} setF={setF} close={close}/></Modal>}
  {modal==='renew'&&<Modal title="Renovar membresía" close={close}><Renew data={data} f={f} setF={setF} close={close}/></Modal>}
  {modal==='payment'&&<Modal title="Registrar pago" close={close}><PaymentForm data={data} f={f} setF={setF} close={close}/></Modal>}
  {modal==='sale'&&<Modal title={'Vender · '+f.product?.name} close={close}><Sale data={data} f={f} setF={setF} close={close}/></Modal>}
  {modal==='stock'&&<Modal title={'Ajustar stock · '+f.variant?.size} close={close}><Stock f={f} setF={setF} close={close}/></Modal>}
  {modal==='product'&&<Modal title="Nuevo producto" close={close}><ProductForm f={f} setF={setF} close={close}/></Modal>}
  {modal==='staff'&&<Modal title="Nuevo personal" close={close}><StaffForm f={f} setF={setF} close={close}/></Modal>}
  {modal==='staffpay'&&<Modal title="Registrar pago a personal" close={close}><StaffPay data={data} f={f} setF={setF} close={close}/></Modal>}
 </div>
}

function Dashboard({data,active,exp,revenue,pending,onRenew,onTab}:any){return <><div className="stats"><Card n={data.athletes.length} l="Deportistas"/><Card n={active.length} l="Membresías activas"/><Card n={exp.length} l="Vencen en 7 días"/><Card n={money(revenue)} l="Ingresos del mes"/></div><div className="grid2"><section><div className="sectionhead"><h2>Próximos vencimientos</h2><button onClick={()=>onTab('memberships')}>Ver todo</button></div>{exp.length?<div className="list">{exp.slice(0,8).map((m:Row)=><div className="line" key={m.id}><div><b>{data.athletes.find((a:Row)=>a.id===m.athlete_id)?.full_name||'—'}</b><small>vence {m.end_date} · {Math.max(0,daysLeft(m.end_date))} días</small></div><button onClick={()=>onRenew(m)}>Renovar</button></div>)}</div>:<Empty text="No hay vencimientos próximos."/>}</section><section><div className="sectionhead"><h2>Actividad</h2><button onClick={()=>onTab('payments')}>Pagos</button></div><div className="kpi"><b>{money(revenue)}</b><span>recaudo confirmado este mes</span></div><div className="minirow"><span>Recordatorios pendientes</span><b>{pending}</b></div><div className="minirow"><span>Ventas registradas</span><b>{data.sales.length}</b></div><div className="minirow"><span>Personal activo</span><b>{data.staff.filter((s:Row)=>s.active).length}</b></div></section></div></>}
function Athletes({rows,q,setQ,canManage,onEdit}:any){return <><div className="toolbar"><input placeholder="Buscar por nombre, documento, teléfono, categoría…" value={q} onChange={e=>setQ(e.target.value)}/></div><Table head={['Deportista','Documento','Teléfono','Categoría','Equipo','Estado','Acción']} rows={rows.map((a:Row)=>[a.full_name,a.document_number||'—',a.phone||'—',a.category||'—',a.team||'—',a.status,a.status==='active'&&canManage?<button onClick={()=>onEdit(a)}>Editar</button>:null])}/></>}
function Memberships({data,onRenew}:any){return <Table head={['Deportista','Plan','Inicio','Vence','Estado','Acción']} rows={data.memberships.map((m:Row)=>{const a=data.athletes.find((x:Row)=>x.id===m.athlete_id),p=data.plans.find((x:Row)=>x.id===m.plan_id);return [a?.full_name||'—',p?.name||'—',m.start_date,m.end_date,<span className={daysLeft(m.end_date)<=7?'warn':''}>{m.status}</span>,m.status==='active'?<button onClick={()=>onRenew(m)}>Renovar</button>:null]})}/>}
function Payments({data}:any){return <><div className="stats three"><Card n={money(data.payments.filter((p:Row)=>p.status==='confirmed'&&p.paid_at?.slice(0,7)===today().slice(0,7)).reduce((n:number,p:Row)=>n+Number(p.amount),0))} l="Recaudo del mes"/><Card n={data.payments.filter((p:Row)=>p.status==='pending').length} l="Pagos pendientes"/><Card n={data.payments.length} l="Movimientos"/></div><Table head={['Fecha','Deportista','Concepto','Método','Valor','Estado']} rows={data.payments.map((p:Row)=>[p.paid_at?.slice(0,10)||p.created_at?.slice(0,10),data.athletes.find((a:Row)=>a.id===p.athlete_id)?.full_name||'—',p.concept,p.method||'—',money(p.amount),p.status])}/></>}
function Products({data,onSale,onAdjust,canManage}:any){return <div className="productgrid">{data.products.map((p:Row)=><section key={p.id}><div className="sectionhead"><div><h2>{p.name}</h2><small>{p.sku||'sin SKU'}</small></div></div>{(p.product_variants||[]).map((v:Row)=><div className="variantrow" key={v.id}><span>{v.size||'Único'}</span><b>{money(v.price)}</b><span className={v.stock<3?'warn':''}>stock {v.stock}</span><div>{canManage&&<button onClick={()=>onAdjust(v)}>Ajustar</button>}<button disabled={v.stock<1} onClick={()=>onSale(v,p)}>Vender</button></div></div>)}</section>)}</div>}
function Staff({data,canManage,onPay}:any){return <><Table head={['Nombre','Rol','Tarifa','Tipo','Activo','Acción']} rows={data.staff.map((s:Row)=>[s.full_name,s.role,money(s.payment_rate),s.rate_type,s.active?'Sí':'No',canManage?<button onClick={()=>onPay(s)}>Registrar pago</button>:null])}/><h2>Historial de pagos</h2><Table head={['Personal','Periodo','Concepto','Valor','Fecha']} rows={data.staffPayments.map((p:Row)=>[data.staff.find((s:Row)=>s.id===p.staff_id)?.full_name||'—',(p.period_start||'—')+' → '+(p.period_end||'—'),p.concept,money(p.amount),p.paid_at?.slice(0,10)||'—'])}/></>}
function Communications({data,exp,pending,onQueue}:any){return <><section><div className="sectionhead"><div><h2>Cola de comunicaciones</h2><small>{pending} pendientes</small></div><button onClick={onQueue}>Generar recordatorios ahora</button></div>{data.notifications.length?<Table head={['Deportista','Canal','Plantilla','Programado','Estado']} rows={data.notifications.map((n:Row)=>[data.athletes.find((a:Row)=>a.id===n.athlete_id)?.full_name||'—',n.channel,n.template,n.scheduled_for?.slice(0,16)||'—',n.status])}/>:<Empty text="La cola está vacía."/>}</section><section><h2>Acciones rápidas</h2>{exp.slice(0,10).map((m:Row)=>{const a=data.athletes.find((x:Row)=>x.id===m.athlete_id);return <div className="line" key={m.id}><div><b>{a?.full_name}</b><small>Vence {m.end_date}</small></div><div className="actions">{a?.email&&<a href={'mailto:'+a.email+'?subject=RIVER%20-%20Renovación%20de%20membresía'}>Email</a>}{a?.phone&&<a target="_blank" href={'https://wa.me/'+a.phone.replace(/\\D/g,'')}>WhatsApp</a>}{a?.phone&&<a href={'sms:'+a.phone}>SMS</a>}</div></div>})}</section></>}
function Audit({rows}:any){return <Table head={['Fecha','Acción','Entidad','ID','Detalles']} rows={rows.map((r:Row)=>[r.created_at?.slice(0,19).replace('T',' '),r.action,r.entity,r.entity_id||'—',JSON.stringify(r.details)])}/>}
function Card({n,l}:any){return <div className="card"><b>{n}</b><span>{l}</span></div>}
function Table({head,rows}:any){return <div className="table"><table><thead><tr>{head.map((h:string)=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r:any[],i:number)=><tr key={i}>{r.map((c:any,j:number)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>}
function Empty({text}:any){return <div className="empty">{text}</div>}
function Modal({title,close,children}:any){return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="modalhead"><h2>{title}</h2><button onClick={close}>×</button></div>{children}</div></div>}
function AthleteForm({f,setF,save,msg}:any){return <FormGrid fields={['full_name','document_number','phone','email','birth_date','category','team']} f={f} setF={setF} msg={msg} save={save}/>}
function FormGrid({fields,f,setF,msg,save}:any){return <div className="formgrid">{fields.map((k:string)=><label key={k}>{k.replaceAll('_',' ')}<input type={k==='birth_date'?'date':'text'} value={f[k]||''} onChange={e=>setF({...f,[k]:e.target.value})}/></label>)}{msg&&<div className="error">{msg}</div>}<button onClick={save}>Guardar</button></div>}
function Register({data,f,setF,close}:any){return <div className="formgrid"><Select label="Deportista" value={f.athlete_id} set={(v:string)=>setF({...f,athlete_id:v})} options={data.athletes.map((a:Row)=>[a.id,a.full_name])}/><Select label="Plan" value={f.plan_id} set={(v:string)=>setF({...f,plan_id:v})} options={data.plans.filter((p:Row)=>p.active).map((p:Row)=>[p.id,money(p.price)+' · '+p.name])}/><label>Inicio<input type="date" value={f.start_date||today()} onChange={e=>setF({...f,start_date:e.target.value})}/></label><label>Inscripción<input type="number" min="0" value={f.registration_amount||0} onChange={e=>setF({...f,registration_amount:e.target.value})}/></label><Select label="Método inscripción" value={f.registration_method||'cash'} set={(v:string)=>setF({...f,registration_method:v})} options={methods}/><Select label="Método mensualidad" value={f.membership_method||'cash'} set={(v:string)=>setF({...f,membership_method:v})} options={methods}/><button onClick={async()=>{if(!f.athlete_id||!f.plan_id)return alert('Selecciona deportista y plan');const r=await supabase.rpc('create_registration',{p_athlete_id:f.athlete_id,p_plan_id:f.plan_id,p_start_date:f.start_date||today(),p_registration_amount:Number(f.registration_amount||0),p_registration_method:f.registration_method||'cash',p_membership_method:f.membership_method||'cash'});if(r.error)alert(r.error.message);else{close();location.reload()}}}>Crear inscripción y registrar pagos</button></div>}
function Renew({data,f,setF,close}:any){return <div className="formgrid"><Select label="Plan" value={f.plan_id} set={(v:string)=>setF({...f,plan_id:v})} options={data.plans.filter((p:Row)=>p.active).map((p:Row)=>[p.id,money(p.price)+' · '+p.name])}/><label>Inicio<input type="date" value={f.start_date||today()} onChange={e=>setF({...f,start_date:e.target.value})}/></label><Select label="Método" value={f.method||'cash'} set={(v:string)=>setF({...f,method:v})} options={methods}/><button onClick={async()=>{if(!f.plan_id)return alert('Selecciona un plan');const r=await supabase.rpc('renew_membership',{p_athlete_id:f.athlete_id,p_plan_id:f.plan_id,p_start_date:f.start_date||today(),p_method:f.method||'cash'});if(r.error)alert(r.error.message);else{alert('Membresía renovada hasta '+r.data.end_date);close();location.reload()}}}>Renovar y registrar pago</button></div>}
const methods=[['cash','Efectivo'],['transfer','Transferencia'],['card','Tarjeta'],['other','Otro']]
function Select({label,value,set,options}:any){return <label>{label}<select value={value||''} onChange={e=>set(e.target.value)}><option value="">Seleccionar</option>{options.map((o:any)=><option key={o[0]} value={o[0]}>{o[1]}</option>)}</select></label>}
function PaymentForm({data,f,setF,close}:any){return <div className="formgrid"><Select label="Deportista" value={f.athlete_id} set={(v:string)=>setF({...f,athlete_id:v})} options={data.athletes.map((a:Row)=>[a.id,a.full_name])}/><Select label="Concepto" value={f.concept||'membership'} set={(v:string)=>setF({...f,concept:v})} options={[['registration','Inscripción'],['membership','Mensualidad'],['product','Producto']]}/><label>Valor<input type="number" min="0" value={f.amount||0} onChange={e=>setF({...f,amount:e.target.value})}/></label><Select label="Método" value={f.method||'cash'} set={(v:string)=>setF({...f,method:v})} options={methods}/><label>Referencia<input value={f.reference||''} onChange={e=>setF({...f,reference:e.target.value})}/></label><button onClick={async()=>{const r=await supabase.from('payments').insert({athlete_id:f.athlete_id||null,concept:f.concept||'membership',amount:Number(f.amount||0),method:f.method,status:'confirmed',reference:f.reference||null,paid_at:new Date().toISOString()});if(r.error)alert(r.error.message);else{close();location.reload()}}}>Registrar pago</button></div>}
function Sale({data,f,setF,close}:any){return <div className="formgrid"><Select label="Deportista (opcional)" value={f.athlete_id} set={(v:string)=>setF({...f,athlete_id:v})} options={data.athletes.map((a:Row)=>[a.id,a.full_name])}/><label>Cantidad<input type="number" min="1" value={f.qty||1} onChange={e=>setF({...f,qty:e.target.value})}/></label><Select label="Método" value={f.method||'cash'} set={(v:string)=>setF({...f,method:v})} options={methods}/><p>Precio unitario: <b>{money(f.variant?.price)}</b> · Stock: <b>{f.variant?.stock}</b></p><button onClick={async()=>{const r=await supabase.rpc('create_sale',{p_athlete_id:f.athlete_id||null,p_variant_id:f.variant.id,p_quantity:Number(f.qty||1),p_method:f.method||'cash'});if(r.error)alert(r.error.message);else{close();location.reload()}}}>Confirmar venta</button></div>}
function Stock({f,setF,close}:any){return <div className="formgrid"><p>Stock actual: <b>{f.variant?.stock}</b></p><label>Ajuste (+/-)<input type="number" value={f.quantity||0} onChange={e=>setF({...f,quantity:e.target.value})}/></label><label>Nota<input value={f.notes||''} onChange={e=>setF({...f,notes:e.target.value})}/></label><button onClick={async()=>{const next=Number(f.variant.stock)+Number(f.quantity||0);if(next<0)return alert('El stock no puede quedar negativo');const a=await supabase.from('product_variants').update({stock:next}).eq('id',f.variant.id);if(a.error)return alert(a.error.message);const mv=await supabase.from('inventory_movements').insert({variant_id:f.variant.id,quantity:Number(f.quantity||0),movement_type:'adjustment',notes:f.notes||null});if(mv.error)return alert(mv.error.message);close();location.reload()}}>Aplicar ajuste</button></div>}
function ProductForm({f,setF,close}:any){const up=(i:number,k:string,v:any)=>{const vs=[...f.variants];vs[i]={...vs[i],[k]:v};setF({...f,variants:vs})};return <div className="formgrid"><label>Nombre<input value={f.name||''} onChange={e=>setF({...f,name:e.target.value})}/></label><label>SKU<input value={f.sku||''} onChange={e=>setF({...f,sku:e.target.value})}/></label><label>Descripción<textarea value={f.description||''} onChange={e=>setF({...f,description:e.target.value})}/></label><h3>Variantes</h3>{f.variants.map((v:any,i:number)=><div className="variantform" key={i}><input placeholder="Talla" value={v.size||''} onChange={e=>up(i,'size',e.target.value)}/><input type="number" placeholder="Precio" value={v.price||0} onChange={e=>up(i,'price',e.target.value)}/><input type="number" placeholder="Stock" value={v.stock||0} onChange={e=>up(i,'stock',e.target.value)}/><button onClick={()=>setF({...f,variants:f.variants.filter((_:any,j:number)=>j!==i)})}>×</button></div>)}<button onClick={()=>setF({...f,variants:[...f.variants,{size:'',price:0,stock:0}]})}>+ Variante</button><button onClick={async()=>{if(!f.name?.trim())return;const p=await supabase.from('products').insert({name:f.name.trim(),sku:f.sku?.trim()||null,description:f.description?.trim()||null,active:true}).select().single();if(p.error)return alert(p.error.message);const vs=f.variants.filter((v:any)=>v.size||Number(v.price)).map((v:any)=>({product_id:p.data.id,size:v.size?.trim()||null,price:Number(v.price||0),stock:Number(v.stock||0)}));if(vs.length){const vr=await supabase.from('product_variants').insert(vs);if(vr.error)return alert(vr.error.message)}close();location.reload()}}>Guardar producto</button></div>}
function StaffForm({f,setF,close}:any){return <div className="formgrid"><label>Nombre completo<input value={f.full_name||''} onChange={e=>setF({...f,full_name:e.target.value})}/></label><label>Documento<input value={f.document_number||''} onChange={e=>setF({...f,document_number:e.target.value})}/></label><label>Teléfono<input value={f.phone||''} onChange={e=>setF({...f,phone:e.target.value})}/></label><label>Correo<input type="email" value={f.email||''} onChange={e=>setF({...f,email:e.target.value})}/></label><Select label="Rol" value={f.role} set={(v:string)=>setF({...f,role:v})} options={[['trainer','Entrenador'],['admin','Administración'],['coordinator','Coordinación'],['other','Otro']]}/><Select label="Tipo de tarifa" value={f.rate_type} set={(v:string)=>setF({...f,rate_type:v})} options={[['monthly','Mensual'],['session','Sesión'],['hourly','Hora'],['fixed','Fija']]}/><label>Tarifa<input type="number" min="0" value={f.payment_rate||0} onChange={e=>setF({...f,payment_rate:e.target.value})}/></label><label>Notas<textarea value={f.notes||''} onChange={e=>setF({...f,notes:e.target.value})}/></label><button onClick={async()=>{const r=await supabase.from('staff_members').insert({...f,payment_rate:Number(f.payment_rate||0),active:true});if(r.error)alert(r.error.message);else{close();location.reload()}}}>Guardar personal</button></div>}
function StaffPay({data,f,setF,close}:any){return <div className="formgrid"><Select label="Personal" value={f.staff_id} set={(v:string)=>setF({...f,staff_id:v})} options={data.staff.map((s:Row)=>[s.id,s.full_name])}/><label>Valor<input type="number" min="0" value={f.amount||0} onChange={e=>setF({...f,amount:e.target.value})}/></label><label>Inicio<input type="date" value={f.period_start||''} onChange={e=>setF({...f,period_start:e.target.value})}/></label><label>Fin<input type="date" value={f.period_end||''} onChange={e=>setF({...f,period_end:e.target.value})}/></label><label>Concepto<input value={f.concept||''} onChange={e=>setF({...f,concept:e.target.value})}/></label><Select label="Método" value={f.method||'transfer'} set={(v:string)=>setF({...f,method:v})} options={methods}/><label>Referencia<input value={f.reference||''} onChange={e=>setF({...f,reference:e.target.value})}/></label><button onClick={async()=>{const r=await supabase.rpc('record_staff_payment',{p_staff_id:f.staff_id,p_amount:Number(f.amount||0),p_period_start:f.period_start,p_period_end:f.period_end,p_concept:f.concept||'Honorarios',p_method:f.method||'transfer',p_reference:f.reference||null});if(r.error)alert(r.error.message);else{close();location.reload()}}}>Registrar pago</button></div>}
function Login({base}:{base:string}){const[e,setE]=useState(''),[p,setP]=useState(''),[m,setM]=useState('');return <div className="login"><div className="loginbox"><img className="brand brand-lg" src={base+'/logo.jpg'} alt="RIVER"/><p>Club OS · gestión integral</p><input autoComplete="email" placeholder="Correo" value={e} onChange={x=>setE(x.target.value)}/><input autoComplete="current-password" placeholder="Contraseña" type="password" value={p} onChange={x=>setP(x.target.value)}/><button onClick={async()=>{const r=await supabase.auth.signInWithPassword({email:e,password:p});setM(r.error?.message||'')}}>Ingresar</button>{m&&<small className="error">{m}</small>}</div></div>}
