'use client'
import {useEffect,useState} from 'react'
import {supabase} from '../lib/supabase'
type A=any
const d=()=>new Date().toISOString().slice(0,10)
const end=(s:string,n:number)=>{const x=new Date(s+'T12:00:00');x.setDate(x.getDate()+n-1);return x.toISOString().slice(0,10)}
const money=(n:number)=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(n||0)
const base=process.env.NEXT_PUBLIC_BASE_PATH||''
const vars={"--img-textura":`url(${base}/fondoTextura.png)`,"--img-camiseta":`url(${base}/fondoCamiseta.png)`,"--img-lineas":`url(${base}/lineas.png)`}as Record<string,string>
export default function Home(){const[s,setS]=useState<A>(),[tab,setTab]=useState('dashboard'),[x,setX]=useState<A>({athletes:[],plans:[],memberships:[],payments:[],products:[],staff:[],staffPayments:[]}),[modal,setModal]=useState(''),[f,setF]=useState<A>({}),[q,setQ]=useState(''),[msg,setMsg]=useState('')
useEffect(()=>{supabase.auth.getSession().then(r=>setS(r.data.session));const z=supabase.auth.onAuthStateChange((_e,v)=>setS(v));return()=>z.data.subscription.unsubscribe()},[])
async function load(){if(!s)return;const [a,p,m,pa,pr,st,sp]=await Promise.all([supabase.from('athletes').select('*').order('full_name'),supabase.from('membership_plans').select('*').eq('active',true),supabase.from('memberships').select('*').order('end_date',{ascending:false}),supabase.from('payments').select('*').order('created_at',{ascending:false}),supabase.from('products').select('*,product_variants(*)').eq('active',true),supabase.from('staff_members').select('*').order('full_name'),supabase.from('staff_payments').select('*').order('created_at',{ascending:false})]);setX({athletes:a.data||[],plans:p.data||[],memberships:m.data||[],payments:pa.data||[],products:pr.data||[],staff:st.data||[],staffPayments:sp.data||[]})}
useEffect(()=>{load()},[s])
if(s===undefined)return <div className="login" style={vars}>Cargando RIVER Club OS…</div>
if(!s)return <Login/>
const active=x.memberships.filter((m:A)=>m.status==='active'&&m.end_date>=d()),exp=active.filter((m:A)=>Math.ceil((new Date(m.end_date).getTime()-Date.now())/86400000)<=7),rev=x.payments.filter((p:A)=>p.status==='confirmed'&&p.paid_at?.slice(0,7)===d().slice(0,7)).reduce((n:number,p:A)=>n+Number(p.amount||0),0)
const nav=['dashboard','athletes','memberships','products','staff','communications']
return <div className="app" style={vars}><aside><img className="brand" src={base+'/logo.jpg'} alt="RIVER"/><small>CLUB OS</small>{nav.map(n=><button className={tab===n?'active':''} onClick={()=>setTab(n)} key={n}>{({dashboard:'Dashboard',athletes:'Deportistas',memberships:'Mensualidades',products:'Productos',staff:'Entrenadores / Administración',communications:'Comunicaciones'}as A)[n]}</button>)}<button onClick={()=>supabase.auth.signOut()}>Cerrar sesión</button></aside><main><header><div><small>RIVER CLUB OS</small><h1>{({dashboard:'Dashboard',athletes:'Deportistas',memberships:'Mensualidades',products:'Productos',staff:'Entrenadores / Administración',communications:'Comunicaciones'}as A)[tab]}</h1></div>{tab==='dashboard'&&<button onClick={()=>{setF({start_date:d(),registration_amount:0});setModal('register')}}>Nueva inscripción</button>}{tab==='athletes'&&<button onClick={()=>{setF({});setModal('athlete')}}>+ Deportista</button>}{tab==='staff'&&<button onClick={()=>{setF({role:'trainer',rate_type:'monthly'});setModal('staff')}}>+ Personal</button>}</header>
{tab==='dashboard'&&<><div className="stats"><Card n={x.athletes.length} l="Deportistas"/><Card n={active.length} l="Mensualidades activas"/><Card n={exp.length} l="Vencen en 7 días"/><Card n={money(rev)} l="Ingresos del mes"/></div><h2>Próximos vencimientos</h2><Table rows={exp.map((m:A)=>[x.athletes.find((a:A)=>a.id===m.athlete_id)?.full_name||'—',m.end_date,<button onClick={async()=>{const p=x.plans[0];const st=d(),en=end(st,Number(p.duration_days));await supabase.from('memberships').insert({athlete_id:m.athlete_id,plan_id:p.id,start_date:st,end_date:en,status:'active'});load()}}>Renovar</button>])}/></>}
{tab==='athletes'&&<><input placeholder="Buscar deportista…" value={q} onChange={e=>setQ(e.target.value)}/><Table rows={x.athletes.filter((a:A)=>a.full_name?.toLowerCase().includes(q.toLowerCase())).map((a:A)=>[a.full_name,a.document_number||'—',a.phone||'—',a.email||'—'])}/></>}
{tab==='memberships'&&<Table rows={x.memberships.map((m:A)=>[x.athletes.find((a:A)=>a.id===m.athlete_id)?.full_name||'—',x.plans.find((p:A)=>p.id===m.plan_id)?.name||'—',m.start_date,m.end_date,m.status])}/>}
{tab==='products'&&<Table rows={x.products.map((p:A)=>[p.name,p.category||'—',p.product_variants?.map((v:A)=>money(v.price)+' · stock '+v.stock).join(' / ')||'—'])}/>}
{tab==='staff'&&<><Table rows={x.staff.map((a:A)=>[a.full_name,a.role,a.rate_type,money(Number(a.payment_rate))])}/><h2>Pagos registrados</h2><Table rows={x.staffPayments.map((p:A)=>[x.staff.find((s:A)=>s.id===p.staff_id)?.full_name||'—',p.concept,money(Number(p.amount)),p.paid_at?.slice(0,10)||'—'])}/></>}
{tab==='communications'&&<section><h2>Recordatorios</h2>{exp.map((m:A)=><div className="line" key={m.id}>{x.athletes.find((a:A)=>a.id===m.athlete_id)?.full_name||'—'} · vence {m.end_date} · email / WhatsApp / SMS</div>)||<p>Sin pendientes.</p>}</section>}
</main>{modal==='athlete'&&<Modal t="Nuevo deportista" close={()=>setModal('')}><Form fields={['full_name','document_number','phone','email']} f={f} setF={setF} save={async()=>{const r=await supabase.from('athletes').insert({...f,status:'active'});setMsg(r.error?.message||'Guardado');if(!r.error){setModal('');load()}}} msg={msg}/></Modal>}{modal==='register'&&<Modal t="Nueva inscripción + mensualidad" close={()=>setModal('')}><Register x={x} f={f} setF={setF} close={()=>{setModal('');load()}}/></Modal>}{modal==='staff'&&<Modal t="Nuevo personal" close={()=>setModal('')}><Form fields={['full_name','document_number','phone','email','payment_rate','notes']} f={f} setF={setF} save={async()=>{const r=await supabase.from('staff_members').insert({...f,payment_rate:Number(f.payment_rate||0),active:true});if(!r.error){setModal('');load()}}} msg={msg}/></Modal>}</div>}
function Login(){const[e,setE]=useState(''),[p,setP]=useState(''),[m,setM]=useState('');return <div className="login" style={vars}><div className="loginjersey"/><div className="loginbox"><img className="brand brand-lg" src={base+'/logo.jpg'} alt="RIVER"/><p>Club OS · gestión integral</p><input placeholder="Correo" value={e} onChange={v=>setE(v.target.value)}/><input placeholder="Contraseña" type="password" value={p} onChange={v=>setP(v.target.value)}/><button onClick={async()=>{const r=await supabase.auth.signInWithPassword({email:e,password:p});setM(r.error?.message||'')}}>Ingresar</button>{m&&<small>{m}</small>}</div></div>}
function Card({n,l}:A){return <div className="card"><b>{n}</b><span>{l}</span></div>}
function Table({rows}:A){return <div className="table"><table><tbody>{rows.map((r:A,i:number)=><tr key={i}>{r.map((c:A,j:number)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>}
function Modal({t,close,children}:A){return <div className="overlay"><div className="modal"><header><h2>{t}</h2><button onClick={close}>×</button></header>{children}</div></div>}
function Form({fields,f,setF,save,msg}:A){return <div className="form">{fields.map((k:string)=><label key={k}>{k.replaceAll('_',' ')}<input type={k.includes('date')?'date':'text'} value={f[k]||''} onChange={e=>setF({...f,[k]:e.target.value})}/></label>)}{msg&&<small>{msg}</small>}<button onClick={save}>Guardar</button></div>}
function Register({x,f,setF,close}:A){return <div className="form"><label>Deportista<select value={f.athlete_id||''} onChange={e=>setF({...f,athlete_id:e.target.value})}><option value="">Seleccionar</option>{x.athletes.map((a:A)=><option key={a.id} value={a.id}>{a.full_name}</option>)}</select></label><label>Plan<select value={f.plan_id||''} onChange={e=>setF({...f,plan_id:e.target.value})}><option value="">Seleccionar</option>{x.plans.map((p:A)=><option key={p.id} value={p.id}>{p.name} · {money(Number(p.price))}</option>)}</select></label><label>Inicio<input type="date" value={f.start_date||d()} onChange={e=>setF({...f,start_date:e.target.value})}/></label><label>Inscripción<input type="number" value={f.registration_amount||0} onChange={e=>setF({...f,registration_amount:e.target.value})}/></label><button onClick={async()=>{const p=x.plans.find((p:A)=>p.id===f.plan_id);const st=f.start_date||d();const en=end(st,Number(p.duration_days));const r=await supabase.from('registrations').insert({athlete_id:f.athlete_id,amount:Number(f.registration_amount||0),registered_at:st,payment_status:'confirmed'}).select().single();if(r.error)return alert(r.error.message);await supabase.from('memberships').insert({athlete_id:f.athlete_id,plan_id:p.id,start_date:st,end_date:en,status:'active'});close()}}>Crear inscripción</button></div>}
